# Travis configuration
#
# Note: building Fortran code is not supported (yet): see https://docs.travis-ci.com/user/language-specific/
#       this is using C as a base and installs gfortran in the test environment
language: c

sudo: required

os: linux
compiler: gcc

env:
  global:
  - FC=gfortran
  - MPIFC=mpif90
  - CC=gcc
  matrix:
  - TEST="" TESTFLAGS=""
  - TEST="--enable-debug" TESTFLAGS=""
  - TEST="--enable-vectorization" TESTFLAGS=""
  - TEST="--enable-openmp" TESTFLAGS="FLAGS_CHECK=-O3"
  - TEST="--enable-openmp" TESTFLAGS="FLAGS_CHECK=\"-fprofile-arcs -ftest-coverage -O0\""

# recommended for MPI projects to unset CC: see https://docs.travis-ci.com/user/languages/c
#before_install:
#  - test -n $CC && unset CC

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install gfortran libgomp1 openmpi-bin libopenmpi-dev
  - echo "compiler versions:" ${FC} ${MPIFC} ${CC}
  - ${FC} --version
  - ${MPIFC} --version
  - ${CC} --version

script:
  - echo "configuration test:" ${TEST} ${TESTFLAGS}
  # test configuration
  - ./configure FC=${FC} MPIFC=${MPIFC} CC=${CC} ${TEST} ${TESTFLAGS}
  - make clean
  # test small example
  - cd EXAMPLES/regional_Greece_small/
  - sed -i "s:^RECORD_LENGTH_IN_MINUTES .*:RECORD_LENGTH_IN_MINUTES = 0.1:" DATA/Par_file
  - ./run_this_example.sh
  # report example
  - cat OUTPUT_FILES/output_mesher.txt
  - cat OUTPUT_FILES/output_solver.txt

# runs example
after_success:
  # code coverage: see example https://github.com/codecov/example-fortran/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash) -s obj/
