# Travis configuration
#
# Note: building Fortran code is not supported (yet): see https://docs.travis-ci.com/user/language-specific/
#       this is using C as a base and installs gfortran in the test environment

language: c
dist: trusty
sudo: required

os: linux
compiler: gcc

env:
  global:
    - FC=gfortran
    - MPIFC=mpif90
    - CC=gcc
    - OMP_NUM_THREADS=2
    - WORKDIR=`pwd`

  matrix:
    # for test cases, we use
    #   TEST    - flags used for configuration
    #   TESTCOV - determines whether or not (0/1) code coverage flags are used
    #   CUDA    - flag for compilation with CUDA
    #   CUDA_VERSION - specifies CUDA toolkit version

    # code coverage: using coverage flags
    - TEST="" TESTCOV=1 TESTMAKE=1 CUDA=false

    # code coverage: vectorization & openmp, using coverage flags
    - TEST="--enable-vectorization" TESTCOV=1 TESTMAKE=2 CUDA=false

    # default test (with > make tests)
    - TEST="" TESTCOV=0 TESTMAKE=0 CUDA=false

    # regional example w/ default configuration
    - TEST="" TESTCOV=0 TESTMAKE=1 CUDA=false

    # regional example w/ vectorization
    - TEST="--enable-vectorization" TESTCOV=0 TESTMAKE=1 CUDA=false

    # regional example w/ vectorization & openmp
    - TEST="--enable-vectorization --enable-openmp" TESTCOV=0 TESTMAKE=1 CUDA=false

    # regional example with debug bounds checking
    - TEST="--enable-debug" TESTCOV=0 TESTMAKE=2 CUDA=false

    # regional example with NGLL = 6
    - TEST="" TESTCOV=0 TESTMAKE=3 CUDA=false

    # globe_small example
    - TEST="--enable-vectorization" TESTCOV=0 TESTMAKE=4 CUDA=false

    # globe_small example with openmp
    - TEST="--enable-vectorization --enable-openmp" TESTCOV=0 TESTMAKE=4 CUDA=false

    # point force example
    - TEST="" TESTCOV=0 TESTMAKE=5 CUDA=false


before_install:
  # informations on git
  - |
    git --version
    git rev-parse --verify HEAD
    git branch -a

  # infos on commits
  - |
    echo "request: Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
    echo "commit : Commit($TRAVIS_COMMIT) Range($TRAVIS_COMMIT_RANGE)"

  # recommended for MPI projects to unset CC: see https://docs.travis-ci.com/user/languages/c
  #- test -n $CC && unset CC

  # updates repository
  - sudo apt-get update


install:
  - bash .travis/run_install.sh


script:
  - bash .travis/run_tests.sh


after_success:
  ###########################################################
  # code coverage
  ###########################################################
  - |
    if [ "$TESTCOV" == "1" ]; then
      gcov --version
      echo `pwd`
      ls -al obj/
    fi

  # produces coverage reports (done manually because of different naming for source & object files)
  - |
    if [ "$TESTCOV" == "1" ]; then
      find obj/ -iname '*.o' | sort | awk '{print "gcov -o obj/ "$1;}'
      # executes gcov-commands
      find obj/ -iname '*.o' | sort | awk '{print "gcov -o obj/ "$1;}' | sh
    fi

  # code coverage:
  # see script : https://github.com/codecov/codecov-bash/blob/master/codecov
  # see example: https://github.com/codecov/example-fortran/blob/master/.travis.yml
  - if [ "$TESTCOV" == "1" ]; then bash <(curl -s https://codecov.io/bash) -X gcov; fi
